openapi: 3.0.0
info:
  title: Comercial-INAL
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: '142'
                    firstName: Alice
                    lastName: Smith
                    verified: false
                    creaeDate: '2021-01-26'
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User by Id
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
            examples:
              Update Role:
                value:
                  role: clientwholesale
              Update Password:
                value:
                  password: string
              Update Personal Data:
                value:
                  firstName: string
                  lastName: string
                  phoneNumber: string
                  city: string
                  password: string
        description: Patch user properties to update.
    delete:
      summary: Remove User by Id
      operationId: delete-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      description: Remove User from DB
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
              required:
                - firstName
                - lastName
                - email
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  password: '123456'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /product:
    get:
      summary: Get List of Products
      tags: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-product
      description: Retrieve information from all products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: Products list
    parameters: []
    post:
      summary: Create new Product
      operationId: post-product
      responses:
        '200':
          description: OK
        '201':
          description: Created
      description: Create new Product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Product created.
  '/product/{productId}':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
        description: Id of a single product
    get:
      summary: Get Product info by Id
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-product-productId
      description: Retrieves the information from a single Product by Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            examples: {}
        description: Product's Information
    put:
      summary: Update Product
      operationId: put-product-productId
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: Updated Product.
    delete:
      summary: Remove Product
      operationId: delete-product-productId
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      description: Deletes Product from Database
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: Deleted Product
  /user/admin:
    post:
      summary: Create User Admin
      operationId: post-user-admin
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '409':
          description: Conflict
      description: Creates new user admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: User information.
  /order:
    get:
      summary: Get all Orders
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-order
      description: Retrieve information from all Orders
    parameters: []
  '/order/{orderId}':
    parameters:
      - schema:
          type: string
        name: orderId
        in: path
        required: true
    get:
      summary: Get Order from Id
      tags: []
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
      operationId: get-order-orderId
      description: Retrieve information from a single order
    put:
      summary: Update Order
      operationId: put-order-orderId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      description: Updates all data from a single Order
    delete:
      summary: Delete Order
      operationId: delete-order-orderId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      description: Deletes a single Order
  /order/byClient/:
    get:
      summary: Get Client's Orders
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-order-byClient
      description: Gets all orders from a single Client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '"clientId"':
                  type: string
    parameters: []
  /auth:
    post:
      summary: Log In
      operationId: post-auth
      responses:
        '200':
          description: OK
          headers:
            x-auth-token:
              schema:
                type: string
              description: jwt with user id and role info
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      description: Authorizes user to login into the website
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '"email"':
                  type: string
                '"password"':
                  type: string
  /resetPassword:
    post:
      summary: Reset password
      operationId: post-resetPassword
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      description: Manages the password reset logic
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
  /order/notDelivered:
    get:
      summary: Get non-delivered Orders
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-order-byDelivered
      description: Retrieves a list of non-delivered orders
    parameters: []
  /user/retailClients:
    get:
      summary: Get all retail clients
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-user-retailClients
      description: Retrieves a list of all retail clients
  /user/wholesaleClients:
    get:
      summary: Get all wholesale clients
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-user-wholesaleClients
      description: 'Retrieves list of all wholesale clients '
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          verified: true
          createDate: '2019-08-24'
          phoneNumber: '2237820183'
          city: La Feliz
          role: retailclient
          password: '123456'
      properties:
        id:
          type: string
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        verified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
        phoneNumber:
          type: string
        city:
          type: string
        role:
          type: string
          enum:
            - admin
            - superadmin
            - retailclient
            - wholesaleclient
        password:
          type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - verified
        - createDate
        - phoneNumber
        - city
        - role
        - password
    Product:
      title: Product
      type: object
      x-examples:
        Medall√≥n de pollo:
          id: '145'
          name: Medallones de pollo
          description: Muy ricos y sabrosos
          imageId: bhcsbdcbasjcb
          type: chicken
          wholesalePrice: 45
          retailPrice: 74
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        imageId:
          type: string
        type:
          type: string
          enum:
            - chicken
            - fish
            - veggie
        wholesalePrice:
          type: number
        retailPrice:
          type: number
    Order:
      title: Order
      type: object
      description: ''
      properties:
        id:
          type: string
        client:
          $ref: '#/components/schemas/User'
        date:
          type: string
        totalPrice:
          type: string
        purchased:
          type: boolean
        productList:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        shippingAddress:
          type: string
        delivered:
          type: boolean
